#include <openssl/md5.h>
#include "constants.h"
int creaserpente(snake *chi,int startx,int starty,int maxx,int maxy);
int creacampo(campo *dove);
void timerPortal(vars *varia);
void start_gioco(vars *varia);
void end_gioco(vars *varia);
void startNcurses(int *larg, int *alt);
void endNcurses();
void snake_direz(snake *chi, int facing);
void comandi(vars *varia);
void riprova(vars *varia);
void comandi_pausa(vars *varia);
void comandi_titolo(vars *varia);
void removepup(campo *dove, int indice);
int presopup(vars *varia, int x, int y);
int presoportal(vars *varia, int x, int y);
int presomuro(vars *varia, int x, int y);
int morsocoda(vars *varia, int x, int y);
void gameover(vars *varia, int causa);
void mangiacibo(vars *varia);
void fisica_serp(vars *varia);
void droppup(vars *varia);
void drop_portal(vars *varia);
void game_step(vars *varia, int *itimer, int *atimer, int *ptimer, int *blaster);
void game_pause_step(vars *varia, int *btimer,int blink);
void game_title_step(vars *varia);
void game_pause_loop(vars *varia, int blink);
void game_loop(vars *varia);
void title_loop(vars *varia);
void blastanim(vars *varia, int *counter);
void nuovoblast(vars *varia,punto *dove, int lung);
wchar_t *drawsez(punto prima, punto qui, punto dopo);
wchar_t *drawtail(punto prima, punto qui);
void bordino(vars *varia);
void grafica(vars *varia, int drawserp);
void overlay_scritta(vars *varia);
void delete_scritta(vars *varia);
void titlescreen_leftpanel(vars *varia);
void titlescreen_rightpanel(vars *varia);
void init_colori(vars *varia);
void checkwin(vars *varia);
void printNexit(vars *varia, int num);
void just_print(vars *varia, int num);
void trimN(char *riga);
int parse_saveline(leaderboard *board, char *line);
int contarighe(FILE *dove);
void md5_4_humans(MD5_CTX *c, char* stringa);
int update_savefile(char nome[maxnome], int score, char *filename, vars *varia);
int comparaz(const void *a, const void *b);
void sort_punteggi(leaderboard *board);
void scrivi_punteggi(int top, int left, int num, vars *varia);
open_savefile(leaderboard *board, char *filename);
void calc_direz(int direz, int *newposx, int *newposy);
void ailog(char *stringa);
void turnleft(int *direz);
void turnright(int *direz);
void clearmatrix(char *matrix, int size);
void colora_dbg(int x,int y,char car);
inline int eligible(int x, int y, vars *varia, char *campo,int larg,int alt);
inline int addcella(vars *varia,char *campo,int larg,int alt);
void ailog_matrix(char *campo, int alt, int larg);
int contalibere(int sx, int sy, char *campo, int larg, int alt,vars *varia);
int findway(int ex, int ey, int dir1, int dir2, vars *varia);
int rotelle(vars *varia, int *px, int *py, int direz);
void grafica_stillosa(vars *varia, int drawserp);
void grafica_sicura(vars *varia, int drawserp);
void bordino_safe(vars *varia);
wchar_t *safe_sez(wchar_t *from);
wchar_t *safe_tail(wchar_t *from);
int crea_snacache(char ***board, int maxx, int maxy);
void blank_snacache(char **board, int maxx, int maxy);
void kill_snacache(char ***board);
void regen_snacache(snake *chi, int maxx,int maxy);
